// authSlice.js

// Import necessary functions from @reduxjs/toolkit

import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the auth slice
const initialState = {
  userInfo: localStorage.getItem("userInfo") ? JSON.parse(localStorage.getItem("userInfo")) : null, // Retrieve user info from localStorage if it exists
};

// Create an auth slice using createSlice function
const authSlice = createSlice({
  name: "auth", // Name of the slice
  initialState, // Initial state defined above
  reducers: {
    setCredentials: (state, action) => {
      state.userInfo = action.payload; // Set user info in the state with payload
      localStorage.setItem("userInfo", JSON.stringify(action.payload)); // Store user info in localStorage
    },
    logout: (state) => {
      state.userInfo = null; // Clear user info from the state
      localStorage.removeItem("userInfo"); // Remove user info from localStorage
    },
  },
});

// Export the actions generated by createSlice
export const { setCredentials, logout } = authSlice.actions;

// Export the reducer generated by createSlice
export default authSlice.reducer;
