// Import necessary constants and the base API slice

import { LOAD_ANALYSIS_URL } from '../constant';
import apiSlice from './apiSlice';

// Extend the base API slice with new endpoints for load analysis
export const loadApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Define a mutation for calculating load analysis
    calculateLoadAnalysis: builder.mutation({
      query: (data) => ({
        url: `${LOAD_ANALYSIS_URL}/calculate`, // Endpoint URL for the mutation
        method: 'POST', // HTTP method for the mutation
        body: data, // Data to be sent in the request body
      }),
      invalidatesTags: ['LoadAnalysis'], // Invalidate 'LoadAnalysis' tags to trigger re-fetching of related data
    }),
  }),
});

// Export the custom hook generated by RTK Query for the calculateLoadAnalysis mutation
export const { useCalculateLoadAnalysisMutation } = loadApiSlice;
